# Base configs
baseurl: "https://bommarito-consulting.github.io/photography"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: ""

# UI configs
title: "Photography by Bommarito Consulting"
subtitle: "Commercial and Scientific Portfolio"
author: "Bommarito Consulting, LLC"
header:
 title: "Photography"
 subtitle: "by BC"
footer:
 name: "Bommarito Consulting, LLC"
 bio: "Commercial and Scientific Photography."
 github: "Commercial and Scientific Photography."
web_design: "AJ"
social_urls:
  github: "https://www.github.com/bommarito-consulting"
